AWSTemplateFormatVersion: 2010-09-09
Description: Create a DynamoDb Table

Parameters:
  TableName:
    Type: String
    Default: Calendar-Year

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "index"
          AttributeType: "S"
        - AttributeName: "user"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "index"
          KeyType: "HASH"
        - AttributeName: "user"
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  DBName:
    Value: !Ref DynamoDBTable
    Description: Database table name
  DBStreamArn:
    Value: !GetAtt DynamoDBTable.StreamArn
    Description: Database stream arn
