AWSTemplateFormatVersion: 2010-09-09
Description: Create a DynamoDb Table

Parameters:
  TableName:
    Type: String
    Default: Calendar-Year

Resources:
  DynamoDBTableTemp:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${TableName}-temp"
      AttributeDefinitions:
        - AttributeName: "index"
          AttributeType: "S"
        - AttributeName: "userSub"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "index"
          KeyType: "HASH"
        - AttributeName: "userSub"
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  DBName:
    Value: !Ref DynamoDBTableTemp
    Description: Database table name
  DBRegion:
    Value: !Ref "AWS::Region"
    Description: Database table name
  DBStreamArn:
    Value: !GetAtt DynamoDBTableTemp.StreamArn
    Description: Database stream arn
