AWSTemplateFormatVersion: 2010-09-09
Description: Create a DynamoDb Table

Parameters:
  TableName:
    Type: String
    Default: Calendar-Year

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "User"
          AttributeType: "S"
        - AttributeName: "Index"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "User"
          KeyType: "RANGE"
        - AttributeName: "Index"
          KeyType: "HASH"
      StreamSpecification: NEW_IMAGE

Outputs:
  DBName:
    Value: !Ref DynamoDBTable
    Description: Database table name
  DBStreamArn:
    Value: !GetAtt DynamoDBTable.StreamArn
    Description: Database stream arn
