version: 0.2

env:
  variables:
    S3_BUCKET_NAME: ""
    PROJECT_REACT_NAME: "calendar"

    IDENTITY_POOL_ID: ""
    COGNITO_REGION: ""
    USERPOOL_ID: ""
    USERPOOL_WEBCLIENT_ID: ""

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing...
      - npm install --prefix ./${PROJECT_REACT_NAME}

  build:
    commands:
      - echo Building...
      - |
        echo "export default { \
          IDENTITY_POOL_ID: '${IDENTITY_POOL_ID}', \
          COGNITO_REGION: '${COGNITO_REGION}', \
          USERPOOL_ID: '${USERPOOL_ID}', \
          USERPOOL_WEBCLIENT_ID: '${USERPOOL_WEBCLIENT_ID}', \
        };" > ./${PROJECT_REACT_NAME}/src/environments/production.js
      - npm run build --prefix ./${PROJECT_REACT_NAME}

  post_build:
    commands:
      - echo syncing files with s3://${S3_BUCKET_NAME}...
      - aws s3 sync ./${PROJECT_REACT_NAME}/build/${PROJECT_REACT_NAME} s3://${S3_BUCKET_NAME} --delete
