AWSTemplateFormatVersion: 2010-09-09
Description: Create a sourceCredential for github

# Do not create this resource if already exist a source credential for
# github at your aws cloud. Only one source by server type may exist (I think)

Parameters:
  SecretName:
    Type: String
    Description: Name of secret (from secrets manager) with GitHub access token
    Default: github-access-token
  SecretKey:
    Type: String
    Description: key from the secret (from secrets manager) with GitHub access token
    Default: GITHUB_ACCESS_TOKEN

Resources:
  CodeBuildSourceCredential:
    Type: "AWS::CodeBuild::SourceCredential"
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: !Sub "{{resolve:secretsmanager:${SecretName}:SecretString:${SecretKey}}}"

Outputs:
  SourceCredential:
    Description: A source credential to be easily ref at clouldformation templates
    Value: !Ref CodeBuildSourceCredential
    Export:
      Name: GitHub-SourceCredentialCFN
