AWSTemplateFormatVersion: 2010-09-09
Description: Create a resolver

Parameters:
  GraphQLApiId:
    Type: String
  DynamoDBDataSourceName:
    Type: String

Resources:
  AppSyncResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref GraphQLApiId
      TypeName: Mutation
      FieldName: addCalendar
      DataSourceName: !Ref DynamoDBDataSourceName
      RequestMappingTemplate: |
        { 
          "version": "2018-05-29",
          "operation": "PutItem",

          #set($user = $context.identity.username)
          #set($userSub = $context.identity.sub)

          "key": {
            "index": $util.dynamodb.toDynamoDBJson($util.autoUlid()),
            "userSub": $util.dynamodb.toDynamoDBJson($userSub)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson({
            $context.arguments.calendar,
            "user":$user
          })
        }
      ResponseMappingTemplate: $util.toJson($context.result)
