AWSTemplateFormatVersion: 2010-09-09
Description: Create a resolver

Parameters:
  GraphQLApiId:
    Type: String
  DynamoDBDataSourceName:
    Type: String

Resources:
  AppSyncResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref GraphQLApiId
      TypeName: Query
      FieldName: cardPreview
      DataSourceName: !Ref DynamoDBDataSourceName
      RequestMappingTemplate: |
        { 
          "version": "2018-05-29",
          "operation": "Scan",

          #set($sub = $context.identity.sub)
          #set($nextToken = $util.defaultIfNullOrBlank($context.arguments.pagination.nextToken, null))
          #set($limit = $util.defaultIfNull($context.arguments.pagination.limit, 20))
          
          "filter": {
            "expression": "userSub = :sub",
            "expressionValues": {
              ":sub": $util.dynamodb.toDynamoDBJson($sub)
            }
          },
          "nextToken": $util.toJson($nextToken),
          "limit": $limit
        }
      ResponseMappingTemplate: |
        #set($context.result.month = $context.result.months[0])
        $util.toJson($context.result)
