AWSTemplateFormatVersion: 2010-09-09
Description: Create a resolver

Parameters:
  GraphQLApiId:
    Type: String
  DynamoDBDataSourceName:
    Type: String

Resources:
  AppSyncResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref GraphQLApiId
      TypeName: Query
      FieldName: calendar
      DataSourceName: !Ref DynamoDBDataSourceName
      RequestMappingTemplate: |
        { 
          "version": "2018-05-29",
          "operation": "GetItem",

          #set($id = $context.arguments.id)
          #set($userSub = $context.identity.sub)

          "key": {
            "index": $util.dynamodb.toDynamoDBJson($id),
            "userSub": $util.dynamodb.toDynamoDBJson($userSub)
          },
          "consistentRead": true
        }
      ResponseMappingTemplate: $util.toJson($context.result)
