AWSTemplateFormatVersion: 2010-09-09
Description: Create a GraphQL from AppSync

Parameters:
  GraphQlApiName:
    Type: String
    Default: Calendar-Year-GraphQL
  UserPoolId:
    Type: String
  UserPoolAwsRegion:
    Type: String
  S3BucketDeploy:
    Type: String
Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref GraphQlApiName
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId: !Ref UserPoolId
        AwsRegion: !Ref UserPoolAwsRegion
        DefaultAction: ALLOW
  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !Ref graphQlApiId
      DefinitionS3Location: https://s3.amazonaws.com/${S3BucketDeploy}/cfn-templates/graphQL/schema.graphql

Outputs:
  GraphQLName:
    Value: !GetAtt GraphQLApi.ApiId
    Description: The GraphQL name
  GraphQLArn:
    Value: !GetAtt GraphQLApi.Arn
    Description: The Amazon Resource Name (ARN) of the API key
  GraphQLUrl:
    Value: !GetAtt GraphQLApi.GraphQLUrl
    Description: The Endpoint URL of the GraphQL API.
